# Site title and subtitle. This is used in _includes/header.html
title: 'CloudShell Developer Guide'
subtitle: ''
description: 'CloudShell is a platform for Cloud Sandbox automation for devops and tests. This is the developer guide and knowledgebase for CloudShell Shell and orchestration scripts developers.'
url: https://qualisystems.github.io
# if you wish to integrate disqus on pages set your shortname here
disqus_shortname: ''
twitter:
  username: qualisystems
logo: '/assets/Quali Logo.png'
# if you use google analytics, add your tracking id here
google_analytics_id: 'UA-81468206-1'

# Enable/show navigation. There are there options:
#   0 - always hide
#   1 - always show
#   2 - show only if posts are present
navigation: 1

collections:
    setting-up:
        output: true
        title: "Setting up for development"

    shells:
        output: true
        title: "Extending CloudShell with Shells"

    orchestration:
        output: true
        title: "Orchestration scripts"

    devops:
        output: true
        title: "Integrating CloudShell into the DevOps Cycle"

    reference:
        output: true
        title: "Reference"

# URL to source code, used in _includes/footer.html
codeurl: 'https://github.com/qualisystems'
mainurl: 'http://www.quali.com'

# Keep as an empty string if served up at the root. If served up at a specific
# path (e.g. on GitHub pages) leave off the trailing slash, e.g. /my-project
baseurl: '/devguide'

# Dates are not included in permalinks
permalink: none

# Syntax highlighting
highlighter: prism

# Since these are pages, it doesn't really matter
future: true

gems:
  - jekyll-sitemap
  - jekyll_github_sample
  - jekyll-lunr-js-search
  - jekyll-seo-tag
# Exclude non-site files
exclude: ['bin', 'README.md']

# Use the kramdown Markdown renderer
markdown: kramdown
redcarpet:
    extensions: [
        'no_intra_emphasis',
        'fenced_code_blocks',
        'autolink',
        'strikethrough',
        'superscript',
        'with_toc_data',
        'tables',
        'hardwrap'
    ]
